### ISSUE TITLE
Minitest failure - example

### ISSUE THREAD

**Issue by mlcooper** [sczizzo/Archive#1]
I would prefer not to call the log rotation file I have generated with this cookbook in `/etc/logrotate.d` be named `example`.  However if it is not named `example`, the minitest fails with this:
```
Failure:
recipe::default#test_0003_has created the example config [/var/chef/minitest/bjn_logrotate/default_test.rb:14]:
Failed assertion, no message given.
```
Can this particular minitest be removed so that I can name my attribute something other than `example`?

**Comment by sczizzo** [comment]
I'm not actually working on anything in this repo anymore (it's just an archive), but you're certainly free to duplicate the code and tailor it to your needs. I probably shouldn't have left Issues turned on; I'll disable that shortly.
